[env:esp32-s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.arduino.usb_cdc = true
board_build.flash_mode = qio
board_build.partitions = default_8MB.csv

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.2

build_flags =
    -Wno-deprecated
    -DCONFIG_LWIP_TCP_SND_BUF=32768
    -DCONFIG_LWIP_TCP_WND=32768

